DivingTracker/DivingTracker.Web/Controllers/MembersController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using DivingTracker.ServiceLayer;
using DivingTracker.ServiceLayer.Enums;
using DivingTracker.Web.Attributes;
using DivingTracker.Web.Models;

namespace DivingTracker.Web.Controllers
{
    public class MembersController : DivingTrackerBaseController
    {
        public MembersController(DivingTrackerEntities databaseContext)
            : base(databaseContext)
        {
        }

        [AuthoriseRoles(SystemRoles.Admin)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var user = DatabaseContext.Users.Find(id);
            if (user == null)
                return HttpNotFound();
            return View(user);
        }

        [AuthoriseRoles(SystemRoles.Admin)]
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var user = DatabaseContext.Users.Find(id);
            DatabaseContext.Users.Remove(user);
            DatabaseContext.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var user = DatabaseContext.Users.Find(id);
            if (user == null)
                return HttpNotFound();

            var qualificationsCompleted = DatabaseContext.UserQualifications.Where(x => x.UserId == id)
                .Select(x => x.Qualification);

            var trainingModuleIds = DatabaseContext.UserCriterions.Where(x => x.UserId == id)
                .Select(x => x.Criterion.ModuleSection.Module.ModuleId);

            var qualificationsInProgress =
                DatabaseContext.Qualifications.Where(x => x.UserQualifications.All(y => y.UserId != id) &&
                                                          x.Modules.Any(y => trainingModuleIds.Contains(y.ModuleId)));

            var model = new UserQualificationsModel(user, qualificationsCompleted, qualificationsInProgress);
            return View(model);
        }

        [AuthoriseRoles(SystemRoles.Admin)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var user = DatabaseContext.Users.Find(id);
            if (user == null)
                return HttpNotFound();

            var model = new UserModel(user);

            ViewBag.SystemRoleId = new SelectList(DatabaseContext.SystemRoles, "SystemRoleId", "Description",
                user.SystemRoleId);
            ViewBag.UserId = new SelectList(DatabaseContext.UserCriterions, "UserId", "UserId", user.UserId);

            return View(model);
        }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [AuthoriseRoles(SystemRoles.Admin)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,SystemLoginId,SystemRoleId,FirstName,Surname,DateOfBirth")] User user)
        {
            if (ModelState.IsValid)
            {
                DatabaseContext.Entry(user).State = EntityState.Modified;
                DatabaseContext.SaveChanges();
                return RedirectToAction("Index");
            }

            var dbUser = DatabaseContext.Users.Find(user.UserId);
            if (dbUser == null)
                return HttpNotFound();

            user.SystemLogin = dbUser.SystemLogin;

            ViewBag.SystemRoleId = new SelectList(DatabaseContext.SystemRoles.Where(x => x.SystemRoleId > 0),
                "SystemRoleId", "Description", user.SystemRoleId);
            ViewBag.UserId = new SelectList(DatabaseContext.UserCriterions, "UserId", "UserId", user.UserId);

            var model = new UserModel(user);
            return View(model);
        }

        [AuthoriseRoles(SystemRoles.Admin, SystemRoles.Instructor)]
        public ActionResult Index()
        {
            var userQualifications = DatabaseContext.UserQualifications;
            var users = DatabaseContext.Users;

            var model = new BranchMembersModel(userQualifications, users);

            return View(model);
        }
    }
}

DivingTracker/DivingTracker.Web/Views/Members/Delete.cshtml
@model DivingTracker.ServiceLayer.User

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SystemLogin.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SystemLogin.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SystemRole.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SystemRole.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserCriteria.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserCriteria.UserId)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default"/> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DivingTracker/DivingTracker.Web/Views/Members/Details.cshtml
@using DivingTracker.ServiceLayer.Enums
@model DivingTracker.Web.Models.UserQualificationsModel

@{
    ViewBag.Title = ViewBag.SiteName + ": Member Details - " + Model.User.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <h1>@Model.User.Name</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="col-md-12 headed-collection card light-background">
            <div class="row">
                <div class="col-md-12 card-header">
                    @if (ViewBag.CurrentUser.SystemRole.SystemRoleId > (int)SystemRoles.Student)
                    {
                        <a href="@Url.Action("Edit", "Members", new {id = Model.User.UserId})" class="btn btn-default enrol">Edit</a>
                    }
                    <h2>Member Details</h2>
                </div>
                <div class="col-md-12 headed-item">
                    <div class="row">
                        <div class="col-md-4">
                            <p>
                                <strong>@Html.DisplayNameFor(model => model.User.Role)</strong>
                            </p>
                        </div>
                        <div class="col-md-8">
                            <p>@Html.DisplayFor(model => model.User.Role)</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <p>
                                <strong>@Html.DisplayNameFor(model => model.User.EmailAddress)</strong>
                            </p>
                        </div>
                        <div class="col-md-8">
                            <p>
                                @Html.DisplayFor(model => model.User.EmailAddress)
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <p>
                                <strong>@Html.DisplayNameFor(model => model.User.DateOfBirth)</strong>
                            </p>
                        </div>
                        <div class="col-md-8">
                            <p>
                                @Html.DisplayFor(model => model.User.DateOfBirth)
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="col-md-12 headed-collection card light-background">
            <div class="row">
                <div class="col-md-12 card-header">
                    <h2>Qualifications</h2>
                </div>
                <div class="col-md-12 headed-item">
                    @if (!Model.QualificationsCompleted.Any())
                    {
                        <p>No qualifications (yet!)</p>
                    }
                    else
                    {
                        foreach (var qualification in Model.QualificationsCompleted)
                        {
                            <div class="row">
                                <div class="col-2">
                                    <p class="@qualification.GlyphClass fa-2x"></p>
                                </div>
                                <div class="col-10">
                                    <p>@qualification.Name
                                </div>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="col-md-12 headed-collection card light-background">
            <div class="row">
                <div class="col-md-12 card-header">
                    @if (ViewBag.CurrentUser.SystemRole.SystemRoleId > (int)SystemRoles.Student)
                    {
                        <a href="@Url.Action("Enrol", "Training", new {id = Model.User.UserId})" class="btn btn-default enrol">Enrol</a>
                    }
                    <h2>Training</h2>
                </div>
                <div class="col-md-12 headed-item">
                    @if (Model.QualificationsInProgress.Select(x => x.Modules).Any())
                    {
                        foreach (var qualification in Model.QualificationsInProgress)
                        {
                            <div class="row">
                                <div class="col-md-12">
                                    <h3>@qualification.Name</h3>
                                    <div class="row">
                                        <div class="col-md-3">
                                            <h4>Modules Complete</h4>
                                            @if (!qualification.Modules.Any(x => x.Completeness >= 1))
                                            {
                                                <p>No modules completed so far</p>
                                            }
                                            else
                                            {
                                                foreach (var module in qualification.Modules.Where(x => x.Completeness >= 1))
                                                {
                                                    <p>@module.Name: @module.Description</p>
                                                }
                                            }
                                        </div>
                                        <div class="col-md-9">
                                            <h4>Modules Remaining <span class="toggle-detail small">(Click here to show/hide more detail)</span></h4>
                                            @foreach (var module in qualification.Modules.Where(x => x.Completeness < 1))
                                            {
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <p>@module.Name: @module.Description</p>
                                                        <h5 class="collapsible">@string.Join("; ", module.ModuleSections.Select(x => x.Name))</h5>
                                                    </div>
                                                </div>
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                    else
                    {
                        <div class="row">
                            <div class="col-md-12">
                                @{
                                    var prefix = Model.User.UserId == ViewBag.CurrentUserId
                                        ? "You are"
                                        : Model.User.FirstName + " is";
                                }
                                <p>@prefix not currently working towards any qualifications.</p>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <p>
            @if (ViewBag.CurrentUser.SystemRoleId > (int)SystemRoles.Student)
            {
                @Html.ActionLink("Edit", "Edit", new {id = Model.User.UserId}, new {@class = "btn btn-primary"})
                <text>&nbsp;</text>
                @Html.ActionLink("Back to List", "Index", null, new {@class = "btn btn-primary"})
            }
        </p>
    </div>
</div>

@section Scripts
{
    <script language="javascript">
        $(document).ready(function() {
            $(".toggle-detail").click(function () {
                debugger;
                $(this).parent().siblings().find('.collapsible').slideToggle();
            });
        });
    </script>
}

DivingTracker/DivingTracker.Web/Views/Members/Edit.cshtml
@model DivingTracker.Web.Models.UserModel

@{
    ViewBag.Title = ViewBag.SiteName + ": Edit Member Details - " + Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-md-12">
        <h1>Editing @Model.Name</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>User</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.UserId)
            @Html.HiddenFor(model => model.CreatedDate)
            @Html.Hidden("BranchId", Model.Branch.BranchId)
            @Html.Hidden("SystemLoginId", Model.SystemLogin.SystemLoginId)

            <div class="form-group">
                @Html.LabelFor(model => model.SystemRole.SystemRoleId, "Role", new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownList("SystemRoleId", null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SystemRole.SystemRoleId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Surname, new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DateOfBirth, new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    <div id="date-of-birth" class="input-group date">
                        @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                        <span class="input-group-addon"><i class="fa fa-calendar"> </i></span>
                        @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
        }
    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/jquery-3.1.1.js")
    @Scripts.Render("~/Scripts/jquery.validate.min.js")
    @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js")
    @Scripts.Render("~/Scripts/moment.js")
    <script type="text/javascript" language="javascript">
        $(document).ready(function() {
            $('#date-of-birth').datetimepicker({
                format: 'L',
                locale: 'en-gb'
            });

            $(function () {
                $.validator.methods.date = function (value, element) {
                    return this.optional(element) || moment(value, "DD/MM/YYYY", true).isValid();
                }
            });
        });
    </script>
}

DivingTracker/DivingTracker.Web/Views/Members/Index.cshtml
@model DivingTracker.Web.Models.BranchMembersModel

@{
    ViewBag.Title = ViewBag.SiteName + ": Branch Members";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var userModel = Model.Users.FirstOrDefault();
}

<div class="row">
    <div class="col-md-12">
        <h1>Branch Members</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="col-md-12 headed-collection card light-background">
            <div class="row">
                <div class="col-md-12 card-header">
                    <h2>Divers</h2>
                </div>
                <div class="col-md-12 headed-item">
                    @foreach (var qualification in Model.DivingQualifications)
                    {
                        <div class="row">
                            <div class="col-2">
                                <p class="@qualification.GlyphClass fa-2x"></p>
                            </div>
                            <div class="col-10">
                                <p>@qualification.Name: @qualification.Count</p>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="col-md-12 headed-collection card light-background">
            <div class="row">
                <div class="col-md-12 card-header">
                    <h2>Instructors</h2>
                </div>
                <div class="col-md-12 headed-item">
                    @foreach (var qualification in Model.InstructorQualifications)
                    {
                        <div class="row">
                            <div class="col-2">
                                <p class="@qualification.GlyphClass fa-2x"></p>
                            </div>
                            <div class="col-10">
                                <p>@qualification.Name: @qualification.Count</p>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-12 headed-collection card light-background">
                    <div class="row">
                        <div class="col-md-12 card-header">
                            <h2>Members</h2>
                        </div>
                        <div class="col-md-12 headed-item">
                            <table id="Branch-members" class="table table-hover table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => userModel.FirstName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => userModel.Surname)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => userModel.DateOfBirth)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => userModel.EmailAddress)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => userModel.Role)
                                    </th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach (var item in Model.Users)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.FirstName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Surname)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.DateOfBirth)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.EmailAddress)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Role)
                                        </td>
                                        <td>
                                            @Html.ActionLink("Edit", "Edit", new {id = item.UserId}) |
                                            @Html.ActionLink("Details", "Details", new {id = item.UserId}) |
                                            @Html.ActionLink("Delete", "Delete", new {id = item.UserId})
                                        </td>
                                    </tr>
                                }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $(document).ready(function() {
            $('#Branch-members').DataTable({
                "order": [[1, "asc"], [0, "asc"]],
                "scrollY": '60vh',
                "scrollCollapse": true,
                "searching": true,
                "paging": false
            });
        });
    </script>
}