DivingTracker/DivingTracker.Web/Controllers/AuthenticationController.cs
using System;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using CommonCode.BusinessLayer;
using CommonCode.BusinessLayer.Helpers;
using DivingTracker.ServiceLayer;
using DivingTracker.ServiceLayer.DataTransferObjects;
using DivingTracker.ServiceLayer.Enums;
using DivingTracker.ServiceLayer.Interfaces;
using DivingTracker.Web.Attributes;
using DivingTracker.Web.Models;

namespace DivingTracker.Web.Controllers
{
    [AllowAnonymous]
    public class AuthenticationController : DivingTrackerBaseController
    {
        private readonly IAuthenticationService _authenticationService;
        private readonly IEmailService _emailService;

        public AuthenticationController(DivingTrackerEntities databaseContext,
            IAuthenticationService authenticationService, IEmailService emailService)
            : base(databaseContext)
        {
            Verify.NotNull(authenticationService, nameof(authenticationService));
            Verify.NotNull(emailService, nameof(emailService));

            _authenticationService = authenticationService;
            _emailService = emailService;
        }

        [HttpGet]
        public ActionResult ConfirmEmail(Guid emailConfirmationToken)
        {
            var authenticationResult = _authenticationService.ConfirmEmail(emailConfirmationToken);
            if (authenticationResult.Type != DataResultType.Success)
                ModelState.AddModelError("",
                    $"The email address could not be confirmed: {authenticationResult.FriendlyMessage}");

            DoLogin(authenticationResult.Value);

            return RedirectToAction("Index", "Home");
        }

        private void DoLogin(User user)
        {
            var systemLogin = DatabaseContext.SystemLogins.Find(user.SystemLoginId);
            if (systemLogin == null)
                return;

            var ticket = new FormsAuthenticationTicket(
                1, systemLogin.EmailAddress,
                DateTime.Now,
                DateTime.Now.AddDays(1),
                false,
                user.SystemRole.Description
            );

            var encryptedTicket = FormsAuthentication.Encrypt(ticket);
            var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);

            Response.Cookies.Add(cookie);

            if (ticket.IsPersistent)
                cookie.Expires = ticket.Expiration;

            FormsAuthentication.SetAuthCookie(systemLogin.EmailAddress, false);
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model)
        {
            if (string.IsNullOrWhiteSpace(model.Password))
            {
                ModelState.AddModelError("", "The password field cannot be blank. Please try again.");
                return Login();
            }

            var authenticationResult = _authenticationService.Login(model.EmailAddress, model.Password);
            if (authenticationResult.Type != DataResultType.Success)
            {
                ModelState.AddModelError("",
                    "The username and password combination was not recognised. Please try again.");
                return Login();
            }

            DoLogin(authenticationResult.Value);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Authorise]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();

            return RedirectToAction("Login");
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegistrationModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var request = model.Map<RegistrationModel, UserRegistrationRequestDto>();
            var registrationResult = _authenticationService.Register(request);
            if (registrationResult.Type != DataResultType.Success)
            {
                ModelState.AddModelError("", registrationResult.FriendlyMessage);
                return View();
            }

            var emailResult = _emailService.Send(EmailType.ConfirmEmail,
                new[] {registrationResult.Value.UserId});
            if (emailResult.Type != DataResultType.Success)
            {
                ModelState.AddModelError("", "We attempted to send an email to you so that " +
                                             "you can confirm your address, but it failed: " +
                                             $"{registrationResult.FriendlyMessage}");
                return View();
            }

            return RedirectToAction("Registered");
        }

        [HttpGet]
        public ActionResult Registered()
        {
            return View();
        }
    }
}

DivingTracker/DivingTracker.Web/Controllers/UserController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using DivingTracker.ServiceLayer;

namespace DivingTracker.Web.Controllers
{
    public class UserController : DivingTrackerBaseController
    {
        public UserController(DivingTrackerEntities databaseContext)
            :base (databaseContext)
        {
        }
        
        // GET: User
        public ActionResult Index()
        {
            var users = DatabaseContext.Users.Include(u => u.SystemLogin).Include(u => u.SystemRole).Include(u => u.UserCriteria);
            return View(users.ToList());
        }

        // GET: User/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = DatabaseContext.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            ViewBag.SystemLoginId = new SelectList(DatabaseContext.SystemLogins, "SystemLoginId", "EmailAddress");
            ViewBag.SystemRoleId = new SelectList(DatabaseContext.SystemRoles, "SystemRoleId", "Description");
            ViewBag.UserId = new SelectList(DatabaseContext.UserCriterias, "UserId", "UserId");
            return View();
        }

        // POST: User/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,CreatedDate,SystemLoginId,SystemRoleId,FirstName,Surname,DateOfBirth")] User user)
        {
            if (ModelState.IsValid)
            {
                DatabaseContext.Users.Add(user);
                DatabaseContext.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SystemLoginId = new SelectList(DatabaseContext.SystemLogins, "SystemLoginId", "EmailAddress", user.SystemLoginId);
            ViewBag.SystemRoleId = new SelectList(DatabaseContext.SystemRoles, "SystemRoleId", "Description", user.SystemRoleId);
            ViewBag.UserId = new SelectList(DatabaseContext.UserCriterias, "UserId", "UserId", user.UserId);
            return View(user);
        }

        // GET: User/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = DatabaseContext.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.SystemLoginId = new SelectList(DatabaseContext.SystemLogins, "SystemLoginId", "EmailAddress", user.SystemLoginId);
            ViewBag.SystemRoleId = new SelectList(DatabaseContext.SystemRoles, "SystemRoleId", "Description", user.SystemRoleId);
            ViewBag.UserId = new SelectList(DatabaseContext.UserCriterias, "UserId", "UserId", user.UserId);
            return View(user);
        }

        // POST: User/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,CreatedDate,SystemLoginId,SystemRoleId,FirstName,Surname,DateOfBirth")] User user)
        {
            if (ModelState.IsValid)
            {
                DatabaseContext.Entry(user).State = EntityState.Modified;
                DatabaseContext.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SystemLoginId = new SelectList(DatabaseContext.SystemLogins, "SystemLoginId", "EmailAddress", user.SystemLoginId);
            ViewBag.SystemRoleId = new SelectList(DatabaseContext.SystemRoles, "SystemRoleId", "Description", user.SystemRoleId);
            ViewBag.UserId = new SelectList(DatabaseContext.UserCriterias, "UserId", "UserId", user.UserId);
            return View(user);
        }

        // GET: User/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = DatabaseContext.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = DatabaseContext.Users.Find(id);
            DatabaseContext.Users.Remove(user);
            DatabaseContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

DivingTracker/DivingTracker.Web/Views/Authentication/Login.cshtml
@model DivingTracker.Web.Models.LoginModel

@{
    Layout = "~/Views/Shared/_External.cshtml";
}

<div class="row">
    <div class="col-12">
        <p>
            <h3>Login</h3>
        </p>
    </div>
</div>
@using (Html.BeginForm("Login", "Authentication", null, FormMethod.Post, new {@class = "form-horizontal col-12"}))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(x => x.EmailAddress, "Email Address", new {@class = "control-label col-12"})
        <div class="col-12">
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="fa fa-envelope"> </i>
                </span>
                @Html.TextBoxFor(x => x.EmailAddress, new {@class = "form-control", placeholder = "Email Address"})
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Password, "Password", new {@class = "control-label col-12"})
        <div class="col-12">
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="fa fa-key"> </i>
                </span>
                @Html.TextBoxFor(x => x.Password, new {@class = "form-control", placeholder = "Password", type = "password"})
            </div>
        </div>
    </div>
    <hr/>
    <div class="pull-right">
        <button class="btn btn-primary" type="submit">Login</button>
    </div>
    <div class="pull-left">
        <p class="align-anchor-with-buttons">Not been here before? @Html.ActionLink("Register", "Register", "User", null) here.</p>
    </div>
}

DivingTracker/DivingTracker.Web/Views/Authentication/Register.cshtml
@model DivingTracker.Web.Models.RegistrationModel

@{
    Layout = "~/Views/Shared/_External.cshtml";
}

<div class="row">
    <div class="col-12">
        <p>
            <h3>Register</h3>
        </p>
    </div>
</div>
@using (Html.BeginForm("Register", "Authentication", null, FormMethod.Post, new {@class = "form-horizontal"}))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(x => x.FirstName, new {@class = "control-label col-3"})
        <div class="col-9">
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="fa fa-user"> </i>
                </span>
                @Html.TextBoxFor(x => x.FirstName, new {@class = "form-control", placeholder = "First Name"})
            </div>
            @Html.ValidationMessageFor(x => x.FirstName, "", new {@class = "help-block label label-danger pull-right"})
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Surname, new {@class = "control-label col-3"})
        <div class="col-9">
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="fa fa-address-book-o"> </i>
                </span>
                @Html.TextBoxFor(x => x.Surname, new {@class = "form-control", placeholder = "Surname"})
            </div>
            @Html.ValidationMessageFor(x => x.Surname, "", new {@class = "help-block label label-danger pull-right"})
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.DateOfBirth, new {@class = "control-label col-3"})
        <div class="col-9">
            <div id="date-of-birth" class="input-group date">
                <span class="input-group-addon">
                    <i class="fa fa-calendar"> </i>
                </span>
                @Html.TextBoxFor(x => x.DateOfBirth, new {@class = "form-control", placeholder = "Date of Birth"})
                <span class="input-group-addon">
                    <i class="fa fa-calendar"> </i>
                </span>
            </div>
            @Html.ValidationMessageFor(x => x.DateOfBirth, "", new {@class = "help-block label label-danger pull-right"})
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.EmailAddress, new {@class = "control-label col-3"})
        <div class="col-9">
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="fa fa-envelope"> </i>
                </span>
                @Html.TextBoxFor(x => x.EmailAddress, new {@class = "form-control", placeholder = "Email Address"})
            </div>
            @Html.ValidationMessageFor(x => x.EmailAddress, "", new {@class = "help-block label label-danger pull-right"})
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Password, new {@class = "control-label col-3"})
        <div class="col-9">
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="fa fa-key"> </i>
                </span>
                @Html.TextBoxFor(x => x.Password, new {@class = "form-control", placeholder = "Password", type = "password"})
            </div>
            @Html.ValidationMessageFor(x => x.Password, "", new {@class = "help-block label label-danger pull-right"})
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.PasswordConfirmation, new {@class = "control-label col-3"})
        <div class="col-9">
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="fa fa-key"> </i>
                </span>
                @Html.TextBoxFor(x => x.PasswordConfirmation, new {@class = "form-control", placeholder = "Confirm Password", type = "password"})
            </div>
            @Html.ValidationMessageFor(x => x.PasswordConfirmation, "", new {@class = "help-block label label-danger pull-right"})
        </div>
    </div>
    <hr/>
    <div class="pull-right">
        <button class="btn btn-primary" type="submit">Register</button>
    </div>
    <div class="pull-left">
        <p class="align-anchor-with-buttons">Already registered? @Html.ActionLink("Login", "Login", "Authentication", null) here.</p>
    </div>
}

@section Scripts
{
    <script type="text/javascript" language="javascript">
        $(document).ready(function() {
            $('#date-of-birth').datetimepicker({
                format: 'L',
                locale: 'en-gb'
            });
        });
    </script>
}

DivingTracker/DivingTracker.Web/Views/Authentication/Registered.cshtml
@model DivingTracker.Web.Models.RegistrationModel

@{
    Layout = "~/Views/Shared/_External.cshtml";
}

<div class="row">
    <div class="col-12">
        <h2>
            Thank you for registering for @ViewBag.SiteName!
        </h2>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <p>
            We have sent you an email confirmation. Please click on the
            link in the email to complete your registration.
        </p>
    </div>
</div>