DivingTracker/DivingTracker.Web/Controllers/QualificationsController.cs
using DivingTracker.ServiceLayer;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using DivingTracker.Web.Models;

namespace DivingTracker.Web.Controllers
{
    public class QualificationsController : DivingTrackerBaseController
    {
        public QualificationsController(DivingTrackerEntities databaseContext)
            : base(databaseContext)
        {
        }

        // GET: Qualifications/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            var qualification = DatabaseContext.Qualifications.Find(id);
            if (qualification == null)
            {
                return HttpNotFound();
            }

            return View(new QualificationModel(qualification));
        }

        // GET: Qualifications/Create
        public ActionResult Create()
        {
            ViewBag.AgencyId = new SelectList(DatabaseContext.Agencies, "AgencyId", "Name");
            ViewBag.QualificationTypeId = new SelectList(DatabaseContext.QualificationTypes, "QualificationTypeId", "Description");
            return View();
        }

        // POST: Qualifications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "QualificationId,AgencyId,QualificationTypeId,Name,Description")] Qualification qualification)
        {
            if (ModelState.IsValid)
            {
                DatabaseContext.Qualifications.Add(qualification);
                DatabaseContext.SaveChanges();
                return RedirectToAction("Index", "Training");
            }

            ViewBag.AgencyId = new SelectList(DatabaseContext.Agencies, "AgencyId", "Name", qualification.AgencyId);
            ViewBag.QualificationTypeId = new SelectList(DatabaseContext.QualificationTypes, "QualificationTypeId", "Description", qualification.QualificationTypeId);
            return View(qualification);
        }

        // GET: Qualifications/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Qualification qualification = DatabaseContext.Qualifications.Find(id);
            if (qualification == null)
            {
                return HttpNotFound();
            }
            ViewBag.AgencyId = new SelectList(DatabaseContext.Agencies, "AgencyId", "Name", qualification.AgencyId);
            ViewBag.QualificationTypeId = new SelectList(DatabaseContext.QualificationTypes, "QualificationTypeId", "Description", qualification.QualificationTypeId);
            return View(qualification);
        }

        // POST: Qualifications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "QualificationId,AgencyId,QualificationTypeId,Name,Description")] Qualification qualification)
        {
            if (ModelState.IsValid)
            {
                DatabaseContext.Entry(qualification).State = EntityState.Modified;
                DatabaseContext.SaveChanges();
                return RedirectToAction("Index", "Training");
            }
            ViewBag.AgencyId = new SelectList(DatabaseContext.Agencies, "AgencyId", "Name", qualification.AgencyId);
            ViewBag.QualificationTypeId = new SelectList(DatabaseContext.QualificationTypes, "QualificationTypeId", "Description", qualification.QualificationTypeId);
            return View(qualification);
        }

        // GET: Qualifications/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Qualification qualification = DatabaseContext.Qualifications.Find(id);
            if (qualification == null)
            {
                return HttpNotFound();
            }
            return View(qualification);
        }

        // POST: Qualifications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Qualification qualification = DatabaseContext.Qualifications.Find(id);
            DatabaseContext.Qualifications.Remove(qualification);
            DatabaseContext.SaveChanges();
            return RedirectToAction("Index", "Training");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                DatabaseContext.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DivingTracker/DivingTracker.Web/Controllers/TrainingController.cs
using System;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web.Mvc;
using DivingTracker.ServiceLayer;
using DivingTracker.ServiceLayer.Enums;
using DivingTracker.Web.Attributes;
using DivingTracker.Web.Models;

namespace DivingTracker.Web.Controllers
{
    [Authorise]
    [AuthoriseRoles(SystemRoles.Instructor, SystemRoles.Admin)]
    public class TrainingController : DivingTrackerBaseController
    {
        public TrainingController(DivingTrackerEntities databaseContext)
            : base(databaseContext)
        {
        }

        public ActionResult Enrol(int id)
        {
            var user = DatabaseContext.Users.Find(id);
            var qualifications = DatabaseContext.Qualifications
                .Where(q => !q.UserQualifications.Select(uq => uq.UserId).Contains(id) // Not already qualified
                    && !q.Modules.Any(m =>
                        m.ModuleSections.Any(ms =>
                            ms.Criteria.Any(c =>
                                c.UserCriterias.Any(uc => uc.UserId == id)))));

            var model = new EnrolModel(user, qualifications);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Enrol(EnrolModel model)
        {
            var qualificationIds = model.EnrolPostModels
                .Where(x => x.Selected)
                .Select(x => x.Qualification.QualificationId);

            var criterionIds = DatabaseContext.Criteria
                .Where(x => qualificationIds.Contains(x.ModuleSection.Module.Qualification.QualificationId))
                .Select(x => x.CriterionId);

            foreach (var criterionId in criterionIds)
            {
                var newUserCriterion = new UserCriterion
                {
                    CriterionId = criterionId,
                    CriterionStatusId = (int)CriterionStatuses.NotStarted,
                    UserId = model.User.UserId,
                    UpdatedDate = DateTime.Now
                };

                DatabaseContext.UserCriterions.Add(newUserCriterion);
            }

            DatabaseContext.SaveChanges();

            return RedirectToAction("Details", "Members", new { id = model.User.UserId });
        }

        [HttpGet]
        public ActionResult Index()
        {
            var qualifications = DatabaseContext.Qualifications.ToArray();
            var model = new Collection<TrainingModel>();

            if (CurrentUser.SystemRole.SystemRoleId < (int)SystemRoles.Instructor)
            {
                var myCriteria = DatabaseContext.UserCriterions.Where(x => x.UserId == CurrentUserId);
                qualifications = qualifications
                    .Where(x => myCriteria.Any(y => y.Criterion.ModuleSection.Module.Qualification.QualificationId ==
                                                    x.QualificationId))
                    .ToArray();
            }

            foreach (var qualification in qualifications)
                model.Add(new TrainingModel(qualification));

            return View(model);
        }

        public ActionResult Qualification(int qualificationId)
        {
            var qualification = DatabaseContext.Qualifications.Find(qualificationId);

            var model = qualification == null
                ? new TrainingModel()
                : new TrainingModel(qualification);

            return View(model);
        }
    }
}

DivingTracker/DivingTracker.Web/Views/Training/Enrol.cshtml
@model DivingTracker.Web.Models.EnrolModel

@{
    ViewBag.Title = ViewBag.SiteName + ": Enrol User";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-md-12">
        <h1>Enrolment for @Model.User.Name</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="col-md-12 headed-collection card light-background">
            <div class="row">
                <div class="col-md-12 card-header">
                    <h2>Qualifications</h2>
                </div>
                <div class="col-md-12 headed-item">
                    @using (Html.BeginForm("Enrol", "Training", null, FormMethod.Post, new {@class = ""}))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(x => x.User.UserId)

                        for (var modelIndex = 0; modelIndex < Model.EnrolPostModels.Count(); ++modelIndex)
                        {
                            <div class="row">
                                <div class="col-12 col-md-1 center">
                                    @Html.HiddenFor(x => x.EnrolPostModels[modelIndex].UserId)
                                    @Html.HiddenFor(x => x.EnrolPostModels[modelIndex].Qualification.QualificationId)
                                    <p>
                                        @Html.CheckBoxFor(x => x.EnrolPostModels[modelIndex].Selected)
                                    </p>
                                </div>
                                <div class="col-12 col-md-11">
                                    <p>@Model.EnrolPostModels[modelIndex].Qualification.Name</p>
                                </div>
                            </div>
                        }
                        <br/>

                        <input type="submit" value="Save" class="btn btn-primary"/>
                        <text>&nbsp;</text>
                        <input type="button" value="Cancel" class="btn btn-default"/>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script language="javascript">
        $(document).ready(function() {
            $(".open-close").on("click",
                function() {
                    $("div.module-users#" + this.classList[1]).slideToggle();
                    $("div.module-table#" + this.classList[1]).slideToggle();
                    $("th.user-name." + this.classList[1]).fadeToggle();
                });
        });
    </script>
}

DivingTracker/DivingTracker.Web/Views/Training/Index.cshtml
@model IEnumerable<DivingTracker.Web.Models.TrainingModel>

@{
    ViewBag.Title = ViewBag.SiteName + ": Qualifications and Training";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <h1>Qualifications and Training</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="col-md-12 headed-collection card light-background">
            <div class="row">
                <div class="col-md-12 card-header">
                    <h2>Courses</h2>
                </div>
                <div class="col-md-12 headed-item">
                    <p>Click on a link below to see the progress tracker for that qualification.</p>
                    @foreach (var trainingModel in Model)
                    {
                        <h4>@trainingModel.Qualification.Name <small> (@trainingModel.Qualification.AgencyName)</small></h4>
                        <p>
                            <a class="btn btn-sm btn-success" href="@Url.Action("Qualification", "Training", new {trainingModel.Qualification.QualificationId})">View Progress Tracker</a>
                            <a class="btn btn-sm btn-warning" href="@Url.Action("Edit", "Qualifications", new {id = trainingModel.Qualification.QualificationId})">Edit Qualification</a>
                        </p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script language="javascript">
        $(document).ready(function () {
            $(".open-close").on("click",
                function () {
                    $("div.module-users#" + this.classList[1]).slideToggle();
                    $("div.module-table#" + this.classList[1]).slideToggle();
                    $("th.user-name." + this.classList[1]).fadeToggle();
                });
        });
    </script>
}

DivingTracker/DivingTracker.Web/Views/Training/MyQualifications.cshtml
@model DivingTracker.Web.Models.TrainingModel

@{
    ViewBag.Title = ViewBag.SiteName + ": My Qualifications and Training";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Qualifications and Training</h1>
@foreach (var module in Model.Modules)
{
    <div class="row">
        <div class="col-md-12">
            @Html.Partial("_TrainingModule", module)
        </div>
    </div>
}

@section Scripts
{
    <script language="javascript">
        $(document).ready(function() {
            $(".open-close").on("click",
                function() {
                    $("div.module-users#" + this.classList[1]).slideToggle();
                    $("div.module-table#" + this.classList[1]).slideToggle();
                    $("th.user-name." + this.classList[1]).fadeToggle();
                });
        });
    </script>
}

DivingTracker/DivingTracker.Web/Views/Training/Qualification.cshtml
@model DivingTracker.Web.Models.TrainingModel

@{
    ViewBag.Title = ViewBag.SiteName + ": Qualifications and Training";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <h1>Qualifications and Training</h1>
        <h2>@Model.Qualification.Name</h2>
    </div>
</div>

@if (Model == null)
{
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-12 headed-collection card light-background">
                <div class="row">
                    <div class="col-md-12 card-header">
                        <h2>Courses</h2>
                    </div>
                    <div class="col-md-12 headed-item">
                        <p>We couldn't find that qualification. Please go back and try again.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
else
{
    foreach (var module in Model.Modules)
    {
        @Html.Partial("_TrainingModule", module)
    }
}

@section Scripts
{
    <script language="javascript">
        $(document).ready(function() {
            $(".open-close").click(function() {
                $("div.collapsible#" + this.classList[2]).slideToggle();
            });
        });
    </script>
}